name: ci-docs

on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/**'
    - 'include/**'
    - 'docs/**'
    - 'CHANGELOG.txt'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
        with:
          repository: bitcoin-core/secp256k1
          path: libsecp256k1
      - name: Build and install libsecp256k1
        run: |
          cd libsecp256k1
          ./autogen.sh
          ./configure --enable-module-recovery --enable-benchmark=no --enable-tests=no
          make
          sudo make install
          pkg-config --cflags --libs libsecp256k1
      - name: Install dependencies
        run: |
          sudo apt-get install doxygen
          sudo apt-get install python3-sphinx
          sudo apt-get install python3-breathe
      - name: Build docs
        run: |
          mkdir build
          cd build
          cmake -DETHC_BUILD_DOCS=ON ..
          make doxygen
          make sphinx
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build/sphinx/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
